### ISSUE TITLE
client无法导入相应的包

### ISSUE THREAD

**Issue by z1047310438** [FedCampus/dyn_flower_android_drf#10]
![image](https://github.com/FedCampus/dyn_flower_android_drf/assets/92215857/63607086-5546-4264-a156-a8c1cada5e84)
![image](https://github.com/FedCampus/dyn_flower_android_drf/assets/92215857/f232f5a1-4d41-4e08-819a-b5fea4aaddf8)

**Comment by z1047310438** [comment]
我build了项目也没有找到import的文件

**Comment by SichangHe** [comment]
Please specify how to reproduce, your system information, and any error messages if you have them.

**Comment by z1047310438** [comment]
I import the client file in the project into android studio, and then make project, it becomes what it is now, and there is no more information.
![image](https://github.com/FedCampus/dyn_flower_android_drf/assets/92215857/6e1dfc6d-bfeb-40e8-b933-48e47efcbc41)

**Comment by z1047310438** [comment]
I should have solved this problem， thank u very mush.

**Comment by z1047310438** [comment]
![image](https://github.com/FedCampus/dyn_flower_android_drf/assets/92215857/d1c520f1-225f-4608-9ee3-0ac21b7c3b68)
The problem is that the file you want to import is in the jar package, which cannot be imported at present
