### ISSUE TITLE
Is the url to download the dataset wrong?

### ISSUE THREAD

**Issue by z1047310438** [FedCampus/dyn_flower_android_drf#11]
![image](https://github.com/FedCampus/dyn_flower_android_drf/assets/92215857/e7bd5142-b4d0-4b86-b23c-ed469c212301)

**Comment by z1047310438** [comment]
https://www.dropbox.com/s/coeixr4kh8ljw6o/cifar10.zip?dl=1.  Is it this one？

**Comment by SichangHe** [comment]
It is correct.
