### ISSUE TITLE
Activity log doesn't show training process

### ISSUE THREAD

**Issue by thinh-dao** [FedCampus/dyn_flower_android_drf#28]
I followed the tutorials to set up the training, and it seems that the Android client has successfully connected to the server hosted on my local machine. I also loaded the data successfully. However, when I click Training, the activity log doesn't show any results from training. I also check the log cat in Android Studio and there don't seem to be any exceptions. 
**System information:**
Server: Apple Mac Pro m1
Client: Samsung A33 5G

**Comment by SichangHe** [comment]
Hi @Ducthinh19102003,

Please provide as many relevant screenshots as possible to help us identify the bug. Thanks!

Steven Hé (Sīchàng)

**Comment by thinh-dao** [comment]
Hi @SichangHe, 
Thank you for the quick reply. It turns out that the training process doesn't start because another task on my machine was using the port 8000. When I terminated it, the training ran successfully. 
However, there are a bug related to the user interface. If I enter the server IP address incorrectly, the app will crash. Furthermore, I think it would help the add the python version in requirements.txt in the backend side, because for me using python version < 3.10 would not work.
Lastly, I would really appreciate if you could briefly explain the training procedure behind the framework. What is the purpose of the Django backend? What if I want to add custom data and aggregating algorithm, pretrained parameters for the global model?

**Comment by SichangHe** [comment]
> It turns out that the training process doesn't start because another task on my machine was using the port 8000. When I terminated it, the training ran successfully.

Great to hear it works.

> However, there are a bug related to the user interface. If I enter the server IP address incorrectly, the app will crash.

Well, this is a demo app, whose only purpose is to verify that the training works. I'm not incentivized to improve its UX.

> Furthermore, I think it would help the add the python version in requirements.txt in the backend side, because for me using python version < 3.10 would not work.

PR welcome.

> Lastly, I would really appreciate if you could briefly explain the training procedure behind the framework.

I'm afraid that this is really just an internal codebase and we don't expect people to depend on it. Our goal does not include educating the public.
That said, you can always read the code yourself, and I will explain quick questions.

> What is the purpose of the Django backend?

1. It makes it possible for us to swap the model used for training without updating the client app.
2. We have a persistent, on-demand service that spawns the Flower server for training.

> What if I want to add custom data and aggregating algorithm, pretrained parameters for the global model?

Modify `backend/train/run.py`.

**Comment by SichangHe** [comment]
Thank you for the thought-out questions and suggestions.

Now that the original problem for this issue is solved, I am closing it. Feel free to open another issue for other problems.
