### ISSUE TITLE
执行Python manager.py migrate 出错

### ISSUE THREAD

**Issue by z1047310438** [FedCampus/dyn_flower_android_drf#9]
![QQ图片20230611160600](https://github.com/FedCampus/dyn_flower_android_drf/assets/92215857/239aa1d6-a22e-4727-bfc0-8b5db9a99d6d)
![QQ图片20230611160659](https://github.com/FedCampus/dyn_flower_android_drf/assets/92215857/c641d90c-5dad-4326-96a1-8a867f9cb4dd)

**Comment by SichangHe** [comment]
I guess you are using a Python < 3.10. Updating would solve the problem.

**Comment by z1047310438** [comment]
ok thanks, my python version is 3.9. I will update my version.

**Comment by z1047310438** [comment]
has been resolved, thank u
